/** Código ISO 3166-1 alpha-2 por nombre de selección (en español). null si se desconoce. */
const CODES: Record<string, string> = {
  ecuador: "ec",
  "costa de marfil": "ci",
  curazao: "cw",
  curaçao: "cw",
  alemania: "de",
  argentina: "ar",
  brasil: "br",
  uruguay: "uy",
  colombia: "co",
  chile: "cl",
  "perú": "pe",
  peru: "pe",
  paraguay: "py",
  bolivia: "bo",
  venezuela: "ve",
  "méxico": "mx",
  mexico: "mx",
  "estados unidos": "us",
  "canadá": "ca",
  canada: "ca",
  "españa": "es",
  espana: "es",
  francia: "fr",
  inglaterra: "gb-eng",
  escocia: "gb-sct",
  gales: "gb-wls",
  portugal: "pt",
  italia: "it",
  "países bajos": "nl",
  "paises bajos": "nl",
  holanda: "nl",
  "bélgica": "be",
  belgica: "be",
  croacia: "hr",
  "japón": "jp",
  japon: "jp",
  "corea del sur": "kr",
  marruecos: "ma",
  senegal: "sn",
  ghana: "gh",
  nigeria: "ng",
  australia: "au",
  "arabia saudita": "sa",
  qatar: "qa",
  suiza: "ch",
  noruega: "no",
  dinamarca: "dk",
  polonia: "pl",
};

export function teamCode(name: string): string | null {
  return CODES[name.trim().toLowerCase()] ?? null;
}
