/** Código ISO 3166-1 alpha-2 por nombre de selección (en español). null si se desconoce. */
const CODES: Record<string, string> = {
  // América del Sur
  ecuador: "ec",
  argentina: "ar",
  brasil: "br",
  uruguay: "uy",
  colombia: "co",
  chile: "cl",
  "perú": "pe",
  peru: "pe",
  paraguay: "py",
  bolivia: "bo",
  venezuela: "ve",

  // América del Norte y Central
  "estados unidos": "us",
  "canadá": "ca",
  canada: "ca",
  "méxico": "mx",
  mexico: "mx",
  panamá: "pa",
  panama: "pa",
  jamaica: "jm",
  "costa rica": "cr",
  honduras: "hn",
  curazao: "cw",
  curaçao: "cw",

  // Europa
  alemania: "de",
  "españa": "es",
  espana: "es",
  francia: "fr",
  portugal: "pt",
  inglaterra: "gb-eng",
  escocia: "gb-sct",
  gales: "gb-wls",
  italia: "it",
  "países bajos": "nl",
  "paises bajos": "nl",
  holanda: "nl",
  "bélgica": "be",
  belgica: "be",
  croacia: "hr",
  suiza: "ch",
  polonia: "pl",
  serbia: "rs",
  ucrania: "ua",
  albania: "al",
  turquía: "tr",
  turkiye: "tr",
  noruega: "no",
  dinamarca: "dk",

  // Asia y Oceanía
  "japón": "jp",
  japon: "jp",
  "corea del sur": "kr",
  corea: "kr",
  "arabia saudita": "sa",
  "arabia saudí": "sa",
  qatar: "qa",
  australia: "au",
  "nueva zelanda": "nz",
  "irán": "ir",
  iran: "ir",
  jordania: "jo",
  uzbekistán: "uz",
  uzbekistan: "uz",

  // África
  "costa de marfil": "ci",
  marruecos: "ma",
  senegal: "sn",
  ghana: "gh",
  nigeria: "ng",
  camerún: "cm",
  camerun: "cm",
  argelia: "dz",
  egipto: "eg",
  "sudáfrica": "za",
  sudafrica: "za",
  túnez: "tn",
  tunez: "tn",
  tanzania: "tz",
  congo: "cd",
};

export function teamCode(name: string): string | null {
  return CODES[name.trim().toLowerCase()] ?? null;
}
